{"uuid": "63a88e1e-c0e2-477a-a18e-0e0ab3fd52e5", "children": ["3214b886-72ce-40fe-b8d4-1073f1335591"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain D:\\chromedriver_win32\\chromedriver.exe using Selenium Manager; Message: Unsuccessful command executed: C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered\n; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\GIT_Projects\\CAW\\tests\\conftest.py\", line 15, in init_driver\n    web_driver = webdriver.Chrome(service=service_obj)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    self.service.path = DriverFinder.get_path(self.service, self.options)\n  File \"C:\\Users\\pappula.l\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 44, in get_path\n    raise NoSuchDriverException(f\"Unable to obtain {service.path} using Selenium Manager; {err}\")\n"}, "start": 1709057084954, "stop": 1709057091798}], "start": 1709057084954, "stop": 1709057092522}